/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedInquilinosRouteImport } from './routes/_authenticated/inquilinos'
import { Route as AuthenticatedImoveisRouteImport } from './routes/_authenticated/imoveis'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedInquilinosIdRouteImport } from './routes/_authenticated/inquilinos.$id'
import { Route as AuthenticatedImoveisIdRouteImport } from './routes/_authenticated/imoveis.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInquilinosRoute = AuthenticatedInquilinosRouteImport.update({
  id: '/inquilinos',
  path: '/inquilinos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImoveisRoute = AuthenticatedImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquilinosIdRoute =
  AuthenticatedInquilinosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInquilinosRoute,
  } as any)
const AuthenticatedImoveisIdRoute = AuthenticatedImoveisIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedImoveisRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/inquilinos': typeof AuthenticatedInquilinosRouteWithChildren
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/inquilinos/$id': typeof AuthenticatedInquilinosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/inquilinos': typeof AuthenticatedInquilinosRouteWithChildren
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/inquilinos/$id': typeof AuthenticatedInquilinosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/imoveis': typeof AuthenticatedImoveisRouteWithChildren
  '/_authenticated/inquilinos': typeof AuthenticatedInquilinosRouteWithChildren
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/imoveis/$id': typeof AuthenticatedImoveisIdRoute
  '/_authenticated/inquilinos/$id': typeof AuthenticatedInquilinosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/despesas'
    | '/imoveis'
    | '/inquilinos'
    | '/pagamentos'
    | '/relatorios'
    | '/imoveis/$id'
    | '/inquilinos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/configuracoes'
    | '/contratos'
    | '/dashboard'
    | '/despesas'
    | '/imoveis'
    | '/inquilinos'
    | '/pagamentos'
    | '/relatorios'
    | '/imoveis/$id'
    | '/inquilinos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/despesas'
    | '/_authenticated/imoveis'
    | '/_authenticated/inquilinos'
    | '/_authenticated/pagamentos'
    | '/_authenticated/relatorios'
    | '/_authenticated/imoveis/$id'
    | '/_authenticated/inquilinos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquilinos': {
      id: '/_authenticated/inquilinos'
      path: '/inquilinos'
      fullPath: '/inquilinos'
      preLoaderRoute: typeof AuthenticatedInquilinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imoveis': {
      id: '/_authenticated/imoveis'
      path: '/imoveis'
      fullPath: '/imoveis'
      preLoaderRoute: typeof AuthenticatedImoveisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquilinos/$id': {
      id: '/_authenticated/inquilinos/$id'
      path: '/$id'
      fullPath: '/inquilinos/$id'
      preLoaderRoute: typeof AuthenticatedInquilinosIdRouteImport
      parentRoute: typeof AuthenticatedInquilinosRoute
    }
    '/_authenticated/imoveis/$id': {
      id: '/_authenticated/imoveis/$id'
      path: '/$id'
      fullPath: '/imoveis/$id'
      preLoaderRoute: typeof AuthenticatedImoveisIdRouteImport
      parentRoute: typeof AuthenticatedImoveisRoute
    }
  }
}

interface AuthenticatedImoveisRouteChildren {
  AuthenticatedImoveisIdRoute: typeof AuthenticatedImoveisIdRoute
}

const AuthenticatedImoveisRouteChildren: AuthenticatedImoveisRouteChildren = {
  AuthenticatedImoveisIdRoute: AuthenticatedImoveisIdRoute,
}

const AuthenticatedImoveisRouteWithChildren =
  AuthenticatedImoveisRoute._addFileChildren(AuthenticatedImoveisRouteChildren)

interface AuthenticatedInquilinosRouteChildren {
  AuthenticatedInquilinosIdRoute: typeof AuthenticatedInquilinosIdRoute
}

const AuthenticatedInquilinosRouteChildren: AuthenticatedInquilinosRouteChildren =
  {
    AuthenticatedInquilinosIdRoute: AuthenticatedInquilinosIdRoute,
  }

const AuthenticatedInquilinosRouteWithChildren =
  AuthenticatedInquilinosRoute._addFileChildren(
    AuthenticatedInquilinosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedImoveisRoute: typeof AuthenticatedImoveisRouteWithChildren
  AuthenticatedInquilinosRoute: typeof AuthenticatedInquilinosRouteWithChildren
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedImoveisRoute: AuthenticatedImoveisRouteWithChildren,
  AuthenticatedInquilinosRoute: AuthenticatedInquilinosRouteWithChildren,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
